import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { api, ApiError } from '../../lib/api'

interface Draft {
  id: string
  title: string
  content_markdown: string
  model_provider: string | null
  model_name: string | null
  created_at: string
  updated_at: string
}

export function DraftEditorPage() {
  const { id: projectId, draftId } = useParams<{ id: string; draftId: string }>()
  const [draft, setDraft] = useState<Draft | null>(null)
  const [content, setContent] = useState('')
  const [isLoading, setIsLoading] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const [saveStatus, setSaveStatus] = useState('')
  const [error, setError] = useState('')

  useEffect(() => {
    if (!draftId) return
    api
      .get<Draft>(`/api/drafts/${draftId}`)
      .then((data) => {
        setDraft(data)
        setContent(data.content_markdown)
      })
      .catch((err) => setError(err instanceof ApiError ? err.message : 'Failed to load draft'))
      .finally(() => setIsLoading(false))
  }, [draftId])

  const handleSave = async () => {
    if (!draftId) return
    setIsSaving(true)
    setSaveStatus('')
    try {
      await api.put(`/api/drafts/${draftId}`, { content_markdown: content })
      setSaveStatus('Saved!')
      setTimeout(() => setSaveStatus(''), 3000)
    } catch (err) {
      setSaveStatus(err instanceof ApiError ? err.message : 'Save failed')
    } finally {
      setIsSaving(false)
    }
  }

  const handleExport = () => {
    window.open(`/api/drafts/${draftId}/export`, '_blank')
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[50vh]">
        <p className="text-gray-500">Loading draft...</p>
      </div>
    )
  }

  if (error || !draft) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-lg shadow p-6 text-center">
          <p className="text-red-600 mb-4">{error || 'Draft not found'}</p>
          <Link
            to={`/projects/${projectId}/synthesis`}
            className="text-blue-600 hover:text-blue-800"
          >
            Back to Synthesis
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-5xl">
      <div className="mb-6 flex items-center justify-between gap-4">
        <Link
          to={`/projects/${projectId}/synthesis`}
          className="text-[15px] text-gray-600 hover:text-gray-800"
        >
          Back to Synthesis
        </Link>
        <div className="flex items-center gap-3">
          {saveStatus && (
            <span
              className={`text-[14px] ${saveStatus === 'Saved!' ? 'text-green-600' : 'text-red-600'}`}
            >
              {saveStatus}
            </span>
          )}
          <button
            onClick={handleSave}
            disabled={isSaving}
            className="rounded-xl bg-blue-600 px-4 py-3 text-[15px] font-semibold text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {isSaving ? 'Saving...' : 'Save'}
          </button>
          <button
            onClick={handleExport}
            className="rounded-xl bg-gray-100 px-4 py-3 text-[15px] text-gray-700 hover:bg-gray-200"
          >
            Export .md
          </button>
        </div>
      </div>

      <div className="rounded-[1.5rem] bg-white shadow-sm">
        <div className="p-4 border-b">
          <h1 className="text-[1.4rem] font-semibold">{draft.title}</h1>
          <p className="mt-1 text-[13px] text-gray-400">
            Generated by {draft.model_provider}/{draft.model_name} · Last updated{' '}
            {new Date(draft.updated_at).toLocaleString()}
          </p>
        </div>
        <textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="h-[600px] w-full resize-none p-6 font-mono text-[15px] leading-7 text-gray-800 focus:outline-none"
          placeholder="Draft content..."
        />
      </div>
    </div>
  )
}
